### PR TITLE
Better reuse of process selection logic

### PR DESCRIPTION
**Pull request by soxofaan**
WIP PR to support #10 #24

### CODE REVIEW

**Comment by soxofaan** [comment]
@m-mohr  @clausmichele This is a pretty big PR and I don't expect you to review it in detail

I just wanted to inform you of what it is about. Some quick highlights
- It is mainly about unified handling of `--processes` and `--process-levels` (and `--experimental`) options for the individual process tests (WP5) and full process graph tests (WP6). In main branch the handling is pretty inconsistent between these WPs.
- It  covers/fixes #10 and #24
- I removed the `processes`, `process_levels` and `skip_experimental` fixtures, and moved that functionality to a pytest plugin under `lib`, which allows to hook into the test collection phase (instead of doing skips at test execution phase)
- for individual process tests (WP5): when using `--processes` and `--process-levels` , process tests of "unselected" processes are now not even collected anymore, e.g. with option `--processes=min`, your test run will only consist of 8 tests (the 8 `min` tests), instead of thousands of tests that will be marked as skipped. This behavior is closer to other test selection features of pytest. And it improves the signal noise ratio of the CLI or HTML report massively if you ask me, allowing you to iterate much more focused on a subset of tests
- for full process graph/workflow tests (WP6): `--processes` and `--experimental` is now supported and follwoed. Also: all process_ids of the  full process graph are now checked to determine if a test should be skipped (instead of depending on that brittle `LEVEL` setting)

**Review by clausmichele — APPROVED** [review]

**Comment by clausmichele** [comment]
> Also: all process_ids of the full process graph are now extracted automatically and checked to determine if a test should be skipped (instead of depending on that brittle LEVEL setting)

This is really cool! I went through the code and seems fine. I just didn't get where the code is initializing the process registry and the list of processes of each defined level, that will be used to check if the process graph contains required processes from that level.

On the workflows side I guess that now the `LEVEL=` parts at the top of the code can be removed.

**Comment by soxofaan** [comment]
> I just didn't get where the code is initializing the process registry and the list of processes of each defined level, that will be used to check if the process graph contains required processes from that level.

FYI: The bootstrapping of these things is triggered  from this pytest "configure" hook:
https://github.com/Open-EO/openeo-test-suite/blob/8ecedb9c254def49c1990c1d21453baef95520da/src/openeo_test_suite/lib/pytest_plugin.py#L66-L76

> On the workflows side I guess that now the LEVEL= parts at the top of the code can be removed.

indeed that was one of the minor followup cleanups I might add

**Comment by soxofaan** [comment]
FYI: I'm going to merge this somewhere today to allows some further finetuning in other tickets

**Comment by m-mohr** [comment]
Is there a way to figure out why something was skipped? Could be with a CLI parameter. I found that valuable to know when developing things.

**Review by m-mohr — CHANGES_REQUESTED** [review]
The runtime slowdown should be investigated

**Comment by soxofaan** [comment]
pushed a quickfix  

and now doing `pytest src/openeo_test_suite/tests/processes/processing/test_example.py --runner=dask`

on main branch:
> 157 failed, 659 passed, 181 skipped, 133 warnings in 5.50s

on process-listing branch:
> 157 failed, 659 passed, 117 skipped, 133 warnings in 5.11s

**Comment by soxofaan** [comment]
> Is there a way to figure out why something was skipped? Could be with a CLI parameter. I found that valuable to know when developing things.

With normal `pytest.skip`s there is always an associated reason that is shown depending on the verbosity level (cli), it is available in the HTML report too.

But I guess you here are referring with "skipped" to tests that are now not being "collected" anymore because of the process selection options?
There is by default not really a way to communicate that. I could add some logging to expose that in some way . Or indeed a cli parameter to use runtime `pytest.skip`s instead of test-collection time skips.

> I found that valuable to know when developing things.

I understand, but as a user of the test suite, using the process selection feature, seeing hundreds of tests scroll by and being listed as skipped in the report gives a bad signal noise ratio

**Comment by m-mohr** [comment]
Yeah, in general I agree that skipped tests should not be shown. But it's imporant for dev to understand why something is skipped, I think.

Thanks for the fix for the slowdown.

**Review by m-mohr — APPROVED** [review]

**Comment by soxofaan** [comment]
> Yeah, in general I agree that skipped tests should not be shown. But it's imporant for dev to understand why something is skipped, I think.

added some minimal logging already in 3984219db7eef5f66f0aeb704a16e13efed08ee8

**Pull request merged**
