### PR TITLE
WP5 indiv process testing: code style improvements

### PR DESCRIPTION
**Pull request by soxofaan**
This is rebased version of PR #21 after it got in messy conflict with main branch

### CODE REVIEW

**Comment by m-mohr** [comment]
I can confirm that #21 and #32 do the same, so #21 can be closed.

Nevertheless, the missing warnings are still a thing. See https://github.com/Open-EO/openeo-test-suite/pull/21#discussion_r1455036302

Otherwise lgtm

**Comment by soxofaan** [comment]
I'll go ahead and merge this, because there is too much risk on conflicts with other issues/PRs I want to work on

**Comment by m-mohr** [comment]
I can't confirm this. From what you've stated above, I'd have assumed that adding `--log-cli-level=WARN` would add the missing warnings back to the log, but it doesn't. They are still missing and we still don't understand why this is the case.

**Comment by m-mohr** [comment]
Okay, I see what happens here:
Instead of showing up in the warnings summary, they now show up in the live log setup:
grafik

That is confusing.

**Comment by m-mohr** [comment]
Moved the issue to #33 to unblock this PR.

**Comment by soxofaan** [comment]
thanks

merged in 0e7a7d766df015d92223bcedae4fe1b2cddae620

**Pull request closed without merging**
